version: '3.9'

services:
  backend:
    image: django-ambassador
    build: ./python
    container_name: 'django-ambassador'
    stdin_open: true
    tty: true
    working_dir: '/app'
    volumes:
      - ..:/app